### ISSUE TITLE
Contact address not showing 

### ISSUE THREAD

**Issue by tykees** [TimLariviere/ElmishContacts#3]
Hello! Nice work.
The address saved with contacts are not displaying properly. could be a cosmetic bug 
![screenshot_2018-09-22-05-52-47](https://user-images.githubusercontent.com/35191441/45913551-7ffe2280-be2c-11e8-8658-cf5979ea3612.png)
Android 5.1
Tecno  Droid pad
And if possible you could improve the app and allow import of contacts, contacts saved on mobile will be displaying on the application.
Consider adding license to your repository.

Thank you!!! ☺

**Comment by TimLariviere** [comment]
Thanks for reporting the issue!
Also seen that when the device is configured with accessibility settings on (bigger fonts).

I'll work on a new version that corrects this and a bunch of new functionalities such as import/export, replacing the primary contacts app, and so on.

**Comment by tykees** [comment]
Good, thanks!
Looking forward to see that and you could also License your repository if you wish :smiley: 
I like the application and you will keep receiving my issues if I have any, including ideas to improve the app.

**Comment by TimLariviere** [comment]
Added a MIT license. :)

**Comment by TimLariviere** [comment]
@tykes Wow, thank you! Lots of good ideas!
I've started the planning of version 1.1, will add some of your suggestions.
https://github.com/TimLariviere/ElmishContacts/projects/3

If you're interested, I'll gladly accept your help with the implementation. :)

**Comment by tykees** [comment]
Glad you like those ideas :smile: 
I would have love to help with the implementation but I am just learning codes (basics) not good enough :) 
I will keep stopping by. Stay Great :muscle:

**Comment by TimLariviere** [comment]
The initial issue should be fixed.
I'm keeping your ideas. :)
